Repository TheR1D/shell_gpt, pull requests merged in 2023-12, with the labels that each got.

#382 Set Home Directory for 'app' User in Dockerfile
  Dockerfile
Labels: bug, docker

#398 System role optimisations for GPT4+ models
  README.md
  sgpt/app.py
  sgpt/config.py
  sgpt/handlers/chat_handler.py
  sgpt/handlers/default_handler.py
  sgpt/handlers/handler.py
  sgpt/role.py
  tests/test_integration.py
Labels: enhancement

#400 Render markdown for default output
  README.md
  sgpt/config.py
  sgpt/handlers/handler.py
  sgpt/role.py
  tests/test_integration.py
Labels: enhancement

#401 REPL multiline documentation and improvements
  README.md
  sgpt/handlers/repl_handler.py
Labels: documentation

#410 REPL conversation bug fix
  sgpt/app.py
  sgpt/handlers/chat_handler.py
  sgpt/role.py
Labels: bug

#414 Added OpenAI SDK dependency
  pyproject.toml
  sgpt/app.py
  sgpt/client.py
  sgpt/config.py
  sgpt/handlers/handler.py
  tests/test_integration.py
  tests/test_unit.py
Labels: enhancement
