Repository TheR1D/shell_gpt, pull requests merged in 2023-06, with the labels that each got.

#267 Shell Integration Install
  README.md
  sgpt/__init__.py
  sgpt/app.py
  sgpt/utils.py
Labels: documentation, enhancement

#263 Model endpoint compatibility
  sgpt/config.py
  sgpt/utils.py
Labels: development

#287 codespell: config, workflow and 1 kinda typo fixed
  .github/workflows/codespell.yml
  pyproject.toml
  scripts/format.sh
  scripts/lint.sh
  tests/test_integration.py
Labels: development

#290 Add option to disable streaming #289
  README.md
  sgpt/client.py
  sgpt/config.py
  sgpt/handlers/handler.py
  tests/test_integration.py
Labels: enhancement

#284 Improve the documentation on the chat mode and REPL mode
  README.md
Labels: documentation
