Repository TheR1D/shell_gpt, pull requests merged in 2023-05, with the labels that each got.

#221 Hide API key from Rich tracebacks
  pyproject.toml
  sgpt/app.py
  sgpt/client.py
  sgpt/config.py
Labels: bug, refactoring

#195 Shell integrations
  sgpt/app.py
  sgpt/make_prompt.py
  sgpt/role.py
  tests/test_integration.py
Labels: enhancement

#226 Ignore comments in the .sgptrc config file
  sgpt/config.py
Labels: bug, enhancement

#249 Describe shell command before executing
  README.md
  sgpt/__init__.py
  sgpt/app.py
  sgpt/handlers/chat_handler.py
  sgpt/handlers/default_handler.py
  sgpt/handlers/handler.py
  sgpt/handlers/repl_handler.py
  sgpt/role.py
  tests/test_integration.py
Labels: bug, enhancement
