Repository TheR1D/shell_gpt, pull requests merged in 2023-03, with the labels that each got.

#49 Release 0.7.0 chat mode, caching, improvements
  .github/workflows/lint_test.yml
  README.md
  pre-push.sh
  setup.py
  sgpt/__init__.py
  sgpt/__main__.py
  sgpt/app.py
  sgpt/chat_gpt.py
  tests/__init__.py
  tests/integrational_tests.py
  tests/unittests.py
Labels: enhancement

#59 feat(docker): added volume for cache persistance
  Dockerfile
  README.md
Labels: enhancement

#62 feat: get api key from OPENAI_API_KEY environment variable
  README.md
  sgpt/app.py
Labels: docker

#63 feat: use new OPENAI_API_KEY variable in the docker part
  Dockerfile
  README.md
Labels: docker

#70 Prompt engineering, OS recognition, improvements
  README.md
  requirements.txt
  setup.py
  sgpt/__init__.py
  sgpt/app.py
  sgpt/chat_gpt.py
  sgpt/make_prompt.py
  tests/integrational_tests.py
Labels: documentation, enhancement

#72 Build Docker image throught GitHub Actions
  .github/workflows/docker.yml
  README.md
Labels: docker

#73 Runtime config, code and file structure improvements
  .github/workflows/lint_test.yml
  README.md
  setup.py
  sgpt/__init__.py
  sgpt/app.py
  sgpt/cache.py
  sgpt/chat_gpt.py
  sgpt/client.py
  sgpt/config.py
  sgpt/utils.py
  tests/integrational_tests.py
  tests/unittests.py
Labels: enhancement, development
