Repository TheR1D/shell_gpt, pull requests merged in 2024-08, with the labels that each got.

#569 Adopt to new function calling format - allow function calling on Groq & other non-openai models
  pyproject.toml
  sgpt/function.py
  sgpt/handlers/handler.py
  tests/test_default.py
  tests/utils.py
Labels: enhancement

#540 Container improvements
  Dockerfile
  README.md
  sgpt/app.py
  sgpt/config.py
  sgpt/role.py
Labels: docker

#607 Minor bug fixes, documentation, release 1.4.4
  README.md
  sgpt/__version__.py
  sgpt/config.py
  sgpt/function.py
  sgpt/handlers/handler.py
Labels: bug, documentation, docker

#608 PyPI deployment fix
  .github/workflows/release.yml
Labels: bug, development
