Repository TheR1D/shell_gpt, pull requests merged in 2024-02, with the labels that each got.

#463 Ollama integration and other backends
  README.md
  pyproject.toml
  sgpt/__version__.py
  sgpt/handlers/handler.py
  tests/test_code.py
  tests/test_default.py
  tests/test_roles.py
  tests/test_shell.py
  tests/utils.py
Labels: enhancement

#444 Fix #422: Markdown formatting for chat history
  README.md
  sgpt/handlers/chat_handler.py
  tests/test_default.py
Labels: bug

#477 Added new config variable API_BASE_URL
  README.md
  pyproject.toml
  sgpt/__main__.py
  sgpt/__version__.py
  sgpt/config.py
  sgpt/handlers/chat_handler.py
  sgpt/handlers/handler.py
  tests/utils.py
Labels: bug

#481 Markdown option and config variable
  sgpt/app.py
  sgpt/config.py
  sgpt/handlers/chat_handler.py
  sgpt/handlers/default_handler.py
  sgpt/handlers/handler.py
  sgpt/handlers/repl_handler.py
  tests/test_code.py
  tests/test_default.py
  tests/test_shell.py
Labels: enhancement

#488 Use OpenAI by default, make LiteLLM optional
  README.md
  pyproject.toml
  sgpt/__version__.py
  sgpt/config.py
  sgpt/handlers/handler.py
  tests/test_code.py
  tests/test_default.py
  tests/test_roles.py
  tests/test_shell.py
  tests/utils.py
Labels: enhancement

#491 Azure integration Wiki page
  README.md
Labels: documentation
